apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin-service
    profile: prod
spec:
  selector:
    matchLabels:
      app: admin-service
      profile: prod
  # 앱이 Ready 상태가 될 때까지 기다리는 시간
  minReadySeconds: 10
  # 롤링 업데이트:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 롤링 업데이트시 스케일아웃할 최대 pod 수
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: admin-pod
      labels:
        app: admin-service
        profile: prod
    spec:
      containers:
        - name: admin-service
          image: ${ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: admin-service
          volumeMounts:
            - name: lotdiz-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "2Gi"
      volumes:
        - name: lotdiz-storage
          persistentVolumeClaim:
            claimName: efs-claim
      restartPolicy: Always

