FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=prod

ARG ORIGINAL_JAR_FILE=./build/libs/admin-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} admin-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/admin-service.jar"]
