server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local,dev
  application:
    name: admin-service
  # config service settings
  cloud:
    config:
      name: admin-service
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
